version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    volumes:
      - kafka_data:/var/lib/kafka/data

  app-consumer:
    build:
      context: ./consumer-app
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
#      KAFKA_TOPIC: nombre-del-topico
    networks:
      - kafka-network

  app-producer:
    build:
      context: ./producer-app
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
#      KAFKA_TOPIC: nombre-del-topico
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  zookeeper_data:
  kafka_data: